#include "../Tools/StringXrefAnalyzer.h"
#include "../Logger/Logger.h"
#include "../vendor/imgui/imgui.h"

#include <algorithm>
#include <atomic>
#include <cstdint>
#include <string>
#include <vector>
#include <unordered_map>
#include <unordered_set>
#include <future>
#include <chrono>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <sstream> // NEW

// Windows + psapi for module/sections
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#ifndef NOMINMAX
#define NOMINMAX
#endif
#include <Windows.h>
#include <Psapi.h>
#undef min
#undef max
#pragma comment(lib, "psapi.lib")

// Scanners
#include "../Analysis/FunctionScanner.h"
#include "../Analysis/PatternScanner.h"

using namespace SapphireHook;

namespace {
	// Load .rdata section range
	static bool GetSectionRange(HMODULE mod, const char* name, uint8_t*& begin, size_t& size) {
		auto base = reinterpret_cast<uint8_t*>(mod);
		auto dos = reinterpret_cast<IMAGE_DOS_HEADER*>(base);
		if (dos->e_magic != IMAGE_DOS_SIGNATURE) return false;
		auto nt = reinterpret_cast<IMAGE_NT_HEADERS*>(base + dos->e_lfanew);
		if (nt->Signature != IMAGE_NT_SIGNATURE) return false;
		auto sec = IMAGE_FIRST_SECTION(nt);
		for (unsigned i = 0; i < nt->FileHeader.NumberOfSections; ++i, ++sec) {
			if (std::memcmp(sec->Name, name, (std::min)(static_cast<size_t>(std::strlen(name)), size_t(8))) == 0) {
				begin = base + sec->VirtualAddress;
				size = sec->Misc.VirtualSize ? sec->Misc.VirtualSize : sec->SizeOfRawData;
				return true;
			}
		}
		return false;
	}

	static void CollectAsciiStrings(uint8_t* rdata, size_t rdataSize, size_t minLen, size_t limit,
		std::vector<std::pair<uintptr_t, std::string>>& out) {
		out.reserve((std::min)(limit, size_t(20000)));
		std::string cur;
		for (size_t i = 0; i < rdataSize; ++i) {
			unsigned char c = rdata[i];
			if (c >= 32 && c <= 126) {
				cur.push_back(static_cast<char>(c));
			}
			else {
				if (cur.size() >= minLen) {
					uintptr_t addr = reinterpret_cast<uintptr_t>(rdata + i - cur.size());
					out.emplace_back(addr, cur);
					if (out.size() >= limit) return;
				}
				cur.clear();
			}
		}
		if (cur.size() >= minLen && out.size() < limit) {
			uintptr_t addr = reinterpret_cast<uintptr_t>(rdata + rdataSize - cur.size());
			out.emplace_back(addr, cur);
		}
	}

	static void CollectUtf16Strings(uint8_t* rdata, size_t rdataSize, size_t minLen, size_t limit,
		std::vector<std::pair<uintptr_t, std::string>>& out) {
		size_t added = 0;
		std::string cur;
		size_t i = 0;
		while (i + 1 < rdataSize && added < limit) {
			uint8_t lo = rdata[i];
			uint8_t hi = rdata[i + 1];
			if (hi == 0 && lo >= 32 && lo <= 126) {
				cur.push_back(static_cast<char>(lo));
				i += 2;
			}
			else {
				if (cur.size() >= minLen) {
					uintptr_t addr = reinterpret_cast<uintptr_t>(rdata + i - cur.size() * 2);
					out.emplace_back(addr, cur);
					++added;
				}
				cur.clear();
				i += 2;
			}
		}
		if (cur.size() >= minLen && added < limit) {
			uintptr_t addr = reinterpret_cast<uintptr_t>(rdata + i - cur.size() * 2);
			out.emplace_back(addr, cur);
		}
	}

	// NEW: Sanitize string for embedding in Python comments
	static std::string SanitizePyString(const std::string& s) {
		std::string out; out.reserve(s.size());
		for (char c : s) {
			switch (c) {
			case '\\': out += "\\\\"; break;
			case '\"': out += "\\\""; break;
			case '\n': out += "\\n"; break;
			case '\r': out += "\\r"; break;
			case '\t': out += "\\t"; break;
			default:
				if (c >= 32 && c <= 126) out += c;
				else {
					char buf[5];
					std::snprintf(buf, sizeof(buf), "\\x%02X", (unsigned char)c);
					out += buf;
				}
			}
		}
		return out;
	}

	// NEW: Export IDA Python script that adds repeatable comments (no renaming)
	static bool ExportIdaComments(const std::vector<StringXrefAnalyzer::XrefRow>& rows, std::string& outPath) {
		using SapphireHook::Logger;

		if (rows.empty()) return false;

		std::filesystem::path baseDir = Logger::GetDefaultTempDir();
		std::error_code ec;
		std::filesystem::create_directories(baseDir, ec);

		const auto now = std::chrono::system_clock::now();
		const auto tt = std::chrono::system_clock::to_time_t(now);
		std::tm tm{};
#if defined(_WIN32)
		localtime_s(&tm, &tt);
#else
		tm = *std::localtime(&tt);
#endif
		std::ostringstream name;
		name << "ida_xref_comments." << std::put_time(&tm, "%Y%m%d.%H%M%S") << ".py";

		std::filesystem::path out = baseDir / name.str();
		std::ofstream ofs(out, std::ios::out | std::ios::trunc);
		if (!ofs.is_open()) {
			LogError(std::string("Export failed: could not open file: ") + out.string());
			return false;
		}

		HMODULE hMod = GetModuleHandleW(nullptr);
		uintptr_t imageBase = reinterpret_cast<uintptr_t>(hMod);

		ofs << "# IDA Pro String XREF Comments\n";
		ofs << "# Generated by SapphireHook StringXrefAnalyzer\n";
		ofs << "import idaapi\nimport idc\n\n";
		ofs << "ida_base = idaapi.get_imagebase()\n";
		ofs << "runtime_base = 0x" << std::hex << imageBase << "\n\n";
		ofs << "def rebase(addr):\n    return addr - runtime_base + ida_base\n\n";
		ofs << "commented = 0\nfailed = 0\n\n";

		for (const auto& r : rows) {
			ofs << "try:\n";
			ofs << "    addr = rebase(0x" << std::hex << r.addr << ")\n";
			ofs << "    c = \"XREF Strings: ";
			for (size_t i = 0; i < r.strings.size(); ++i) {
				if (i) ofs << " | ";
				ofs << SanitizePyString(r.strings[i]);
			}
			ofs << "\"\n";
			ofs << "    idc.set_func_cmt(addr, c, 0)\n";
			ofs << "    commented += 1\n";
			ofs << "except Exception as e:\n";
			ofs << "    failed += 1\n\n";
		}
		ofs << "print(f\"Done. {commented} comments added, {failed} failed.\")\n";
		ofs.flush();
		ofs.close();

		outPath = out.string();
		return true;
	}

	// Read printable ASCII string at address (stop at NUL / non-printable), minLen gate
	static bool ReadAsciiString(uintptr_t addr, std::string& out, size_t minLen = 3, size_t maxLen = 512)
	{
		out.clear();
		if (!addr) return false;

		// Quick memory validation
		MEMORY_BASIC_INFORMATION mbi{};
		if (VirtualQuery(reinterpret_cast<LPCVOID>(addr), &mbi, sizeof(mbi)) == 0) return false;
		const DWORD readable = PAGE_READONLY | PAGE_READWRITE | PAGE_WRITECOPY |
			PAGE_EXECUTE_READ | PAGE_EXECUTE_READWRITE | PAGE_EXECUTE_WRITECOPY;
		if (mbi.State != MEM_COMMIT || (mbi.Protect & readable) == 0) return false;

		const char* p = reinterpret_cast<const char*>(addr);
		for (size_t i = 0; i < maxLen; ++i) {
			char c = 0;
			__try { c = p[i]; }
			__except (EXCEPTION_EXECUTE_HANDLER) { return false; }

			if (c == '\0') break;
			if (static_cast<unsigned char>(c) < 32 || static_cast<unsigned char>(c) > 126) return false;
			out.push_back(c);
		}
		return out.size() >= minLen;
	}

	static bool ReadUtf16AsciiString(uintptr_t addr, std::string& out, size_t minLen = 3, size_t maxCP = 512)
	{
		out.clear();
		if (!addr) return false;

		MEMORY_BASIC_INFORMATION mbi{};
		if (VirtualQuery(reinterpret_cast<LPCVOID>(addr), &mbi, sizeof(mbi)) == 0) return false;
		const DWORD readable = PAGE_READONLY | PAGE_READWRITE | PAGE_WRITECOPY |
			PAGE_EXECUTE_READ | PAGE_EXECUTE_READWRITE | PAGE_EXECUTE_WRITECOPY;
		if (mbi.State != MEM_COMMIT || (mbi.Protect & readable) == 0) return false;

		const uint8_t* p = reinterpret_cast<const uint8_t*>(addr);
		for (size_t i = 0; i < maxCP; ++i) {
			uint8_t lo = 0, hi = 0;
			__try {
				lo = p[i * 2 + 0];
				hi = p[i * 2 + 1];
			}
			__except (EXCEPTION_EXECUTE_HANDLER) { return false; }

			// terminator
			if (lo == 0 && hi == 0) break;
			// expect ASCII in UTF-16LE (hi==0)
			if (hi != 0 || lo < 32 || lo > 126) return false;

			out.push_back(static_cast<char>(lo));
		}
		return out.size() >= minLen;
	}

	// Collect strings referenced by RIP-relative instructions within the function window
	static std::vector<std::string> CollectStringsFromFunction(uintptr_t fnStart,
		size_t maxScanBytes = 0x300, size_t minLen = 3)
	{
		std::vector<std::string> out;
		if (!fnStart) return out;

		// PE sections
		HMODULE mod = GetModuleHandleW(nullptr);
		auto rdata = SapphireHook::PatternScanner::GetPESection(mod, ".rdata");
		auto data = SapphireHook::PatternScanner::GetPESection(mod, ".data");

		auto inReadableData = [&](uintptr_t target) -> bool {
			// Check against .rdata or .data
			if (rdata && target >= reinterpret_cast<uintptr_t>(rdata.baseAddress) &&
				target < (reinterpret_cast<uintptr_t>(rdata.baseAddress) + rdata.size))
				return true;
			if (data && target >= reinterpret_cast<uintptr_t>(data.baseAddress) &&
				target < (reinterpret_cast<uintptr_t>(data.baseAddress) + data.size))
				return true;
			return false;
			};

		std::unordered_set<std::string> uniq;
		const std::byte* ip = reinterpret_cast<const std::byte*>(fnStart);
		for (size_t off = 0; off < maxScanBytes; ) {
			uintptr_t target = 0;
			size_t insLen = 0;
			// Use existing instruction helper; returns true for RIP-rel instructions and gives target+length
			if (SapphireHook::PatternScanner::ParseRipRelativeInstruction(ip + off, target, insLen) && insLen > 0) {
				if (inReadableData(target)) {
					std::string s;
					// Try ASCII first, then UTF-16(LE ASCII)
					if (ReadAsciiString(target, s, minLen) || ReadUtf16AsciiString(target, s, minLen)) {
						if (uniq.insert(s).second) out.push_back(std::move(s));
					}
				}
				off += insLen;
			}
			else {
				// Fallback: step 1 byte on unknown instruction
				off += 1;
			}
		}
		return out;
	}

	// Parse address text: supports 0x..., decimal, IDA absolute rebased to runtime, or RVA prefixed with "rva:"
	static bool ParseAddressFlexible(const std::string& txt, uintptr_t& outAddr)
	{
		outAddr = 0;
		if (txt.empty()) return false;

		std::string s = txt;
		// trim
		s.erase(s.begin(), std::find_if(s.begin(), s.end(), [](unsigned char c) { return !std::isspace(c); }));
		s.erase(std::find_if(s.rbegin(), s.rend(), [](unsigned char c) { return !std::isspace(c); }).base(), s.end());

		HMODULE mod = GetModuleHandleW(nullptr);
		const uintptr_t base = reinterpret_cast<uintptr_t>(mod);

		// rva:<hex|dec>
		if (s.rfind("rva:", 0) == 0 || s.rfind("RVA:", 0) == 0) {
			std::string tail = s.substr(4);
			uint64_t v = 0;
			if (tail.rfind("0x", 0) == 0 || tail.rfind("0X", 0) == 0) {
				std::stringstream ss; ss << std::hex << tail.substr(2); ss >> v;
			}
			else {
				std::stringstream ss; ss << tail; ss >> v;
			}
			outAddr = base + static_cast<uintptr_t>(v);
			return outAddr != 0;
		}

		// Hex
		if (s.rfind("0x", 0) == 0 || s.rfind("0X", 0) == 0) {
			uint64_t v = 0;
			std::stringstream ss; ss << std::hex << s.substr(2); ss >> v;
			if (!ss.fail()) {
				outAddr = static_cast<uintptr_t>(v);
				// Rebase IDA abs if needed
				constexpr uintptr_t IDA_BASE = 0x0000000140000000ULL;
				if (outAddr >= IDA_BASE && outAddr < IDA_BASE + 0x20000000ULL) {
					outAddr = (outAddr - IDA_BASE) + base;
				}
				return true;
			}
		}

		// Decimal
		{
			uint64_t v = 0;
			std::stringstream ss; ss << s; ss >> v;
			if (!ss.fail()) {
				outAddr = static_cast<uintptr_t>(v);
				// Also rebase if looks like IDA abs in decimal range
				constexpr uintptr_t IDA_BASE = 0x0000000140000000ULL;
				if (outAddr >= IDA_BASE && outAddr < IDA_BASE + 0x20000000ULL) {
					outAddr = (outAddr - IDA_BASE) + base;
				}
				return true;
			}
		}

		return false;
	}
} // anonymous

StringXrefAnalyzer::StringXrefAnalyzer() = default;
StringXrefAnalyzer::~StringXrefAnalyzer()
{
	CancelAnalysis();
}

void StringXrefAnalyzer::Initialize()
{
	LogInfo("StringXrefAnalyzer initialized");
}

void StringXrefAnalyzer::RenderMenu()
{
	if (ImGui::MenuItem(GetDisplayName(), nullptr, m_windowOpen))
		m_windowOpen = !m_windowOpen;
}

void StringXrefAnalyzer::RenderWindow()
{
	if (!m_windowOpen) return;

	ImGui::SetNextWindowSize(ImVec2(900, 600), ImGuiCond_FirstUseEver);
	if (!ImGui::Begin(GetDisplayName(), &m_windowOpen)) {
		ImGui::End();
		return;
	}

	// Controls
	ImGui::Text("String \xe2\x86\x92 Function XREF analysis");
	ImGui::Separator();

	ImGui::SetNextItemWidth(120);
	ImGui::InputInt("Min string length", &m_state.minLen);
	if (m_state.minLen < 3) m_state.minLen = 3;

	ImGui::SameLine();
	ImGui::SetNextItemWidth(200);
	int maxPerFn = static_cast<int>(m_state.maxStringsPerFn);
	if (ImGui::InputInt("Max strings per function", &maxPerFn)) {
		if (maxPerFn < 1) maxPerFn = 1;
		if (maxPerFn > 16) maxPerFn = 16;
		m_state.maxStringsPerFn = static_cast<size_t>(maxPerFn);
	}

	if (!m_state.running) {
		if (ImGui::Button("Start Analysis")) {
			StartAnalysis(m_state.minLen, m_state.maxStringsPerFn);
		}
		ImGui::SameLine();
		if (!m_state.rows.empty()) {
			if (ImGui::Button("Export Results (.txt)")) {
				std::string path;
				if (ExportResultsToText(path)) {
					LogInfo(std::string("String XREF results exported to: ") + path);
				}
				else {
					LogError("Failed to export String XREF results");
				}
			}
			ImGui::SameLine();
			// NEW: IDA comments export (no renaming)
			if (ImGui::Button("Export IDA Comments (.py)")) {
				std::string path;
				if (ExportIdaComments(m_state.rows, path)) {
					LogInfo(std::string("IDA comments script exported to: ") + path);
				}
				else {
					LogError("Failed to export IDA comments script");
				}
			}
		}
	}
	else {
		if (ImGui::Button("Cancel")) {
			CancelAnalysis();
		}
		ImGui::SameLine();
		ImGui::TextDisabled("%s", m_state.status.c_str());
	}

	if (m_state.running) {
		float frac = (m_state.mapTotal > 0)
			? static_cast<float>(m_state.mapProcessed.load(std::memory_order_relaxed)) / static_cast<float>(m_state.mapTotal)
			: 0.0f;
		ImGui::ProgressBar(frac, ImVec2(-1, 0), m_state.status.c_str());
	}
	else if (!m_state.status.empty()) {
		ImGui::TextColored(ImVec4(0.5f, 1.0f, 0.5f, 1.0f), "%s", m_state.status.c_str());
	}

	ImGui::Separator();
	ImGui::Text("ASCII strings: %zu | UTF-16 strings: %zu | Functions: %zu",
		m_state.totalAscii, m_state.totalUtf16, m_state.rows.size());

	// NEW: String search panel (no heuristics; substring match)
	if (!m_state.rows.empty()) {
		ImGui::Separator();
		if (ImGui::CollapsingHeader("String search", ImGuiTreeNodeFlags_DefaultOpen)) {
			static char query[256] = { 0 };
			ImGui::SetNextItemWidth(320);
			ImGui::InputText("Query", query, sizeof(query));
			ImGui::SameLine();
			ImGui::TextDisabled("Substring match across function strings");

			// Collect matches
			struct Hit { uintptr_t addr; std::string preview; };
			std::vector<Hit> hits;
			std::string q = query;
			if (!q.empty()) {
				for (const auto& r : m_state.rows) {
					bool matched = false;
					std::string preview;
					for (const auto& s : r.strings) {
						if (s.find(q) != std::string::npos) {
							matched = true;
							if (!preview.empty()) preview += " | ";
							preview += s;
							if (preview.size() > 200) { preview += " ..."; break; }
						}
					}
					if (matched) hits.push_back({ r.addr, std::move(preview) });
					if (hits.size() >= 1000) break; // throttle UI
				}
			}

			if (!q.empty()) {
				ImGui::TextDisabled("Matches: %zu", hits.size());
				if (ImGui::BeginTable("str_hits", 3, ImGuiTableFlags_Borders | ImGuiTableFlags_RowBg | ImGuiTableFlags_SizingStretchProp)) {
					ImGui::TableSetupColumn("VA", ImGuiTableColumnFlags_WidthFixed, 170.f);
					ImGui::TableSetupColumn("RVA", ImGuiTableColumnFlags_WidthFixed, 120.f);
					ImGui::TableSetupColumn("Preview", ImGuiTableColumnFlags_WidthStretch);
					ImGui::TableHeadersRow();

					const uintptr_t imageBase = reinterpret_cast<uintptr_t>(GetModuleHandleW(nullptr));
					for (const auto& h : hits) {
						ImGui::TableNextRow();
						ImGui::TableSetColumnIndex(0);
						ImGui::Text("0x%016llX", static_cast<unsigned long long>(h.addr));
						ImGui::TableSetColumnIndex(1);
						ImGui::Text("0x%08llX", static_cast<unsigned long long>(h.addr - imageBase));
						ImGui::TableSetColumnIndex(2);
						ImGui::TextWrapped("%s", h.preview.c_str());
					}
					ImGui::EndTable();

					// Copy addresses helper
					if (ImGui::Button("Copy VAs")) {
						std::ostringstream ss;
						for (const auto& h : hits)
							ss << "0x" << std::hex << h.addr << "\n";
						auto text = ss.str();
						if (OpenClipboard(nullptr)) {
							EmptyClipboard();
							HGLOBAL hg = GlobalAlloc(GMEM_MOVEABLE, text.size() + 1);
							if (hg) {
								memcpy(GlobalLock(hg), text.c_str(), text.size() + 1);
								GlobalUnlock(hg);
								SetClipboardData(CF_TEXT, hg);
							}
							CloseClipboard();
						}
					}
					ImGui::SameLine();
					if (ImGui::Button("Copy RVAs")) {
						std::ostringstream ss;
						const uintptr_t imageBase2 = reinterpret_cast<uintptr_t>(GetModuleHandleW(nullptr));
						for (const auto& h : hits)
							ss << "0x" << std::hex << (h.addr - imageBase2) << "\n";
						auto text = ss.str();
						if (OpenClipboard(nullptr)) {
							EmptyClipboard();
							HGLOBAL hg = GlobalAlloc(GMEM_MOVEABLE, text.size() + 1);
							if (hg) {
								memcpy(GlobalLock(hg), text.c_str(), text.size() + 1);
								GlobalUnlock(hg);
								SetClipboardData(CF_TEXT, hg);
							}
							CloseClipboard();
						}
					}
				}
			}
		}
	}

	ImGui::Separator();

	// Results table
	if (!m_state.rows.empty()) {
		if (ImGui::BeginTable("xref_rows", 3, ImGuiTableFlags_Borders | ImGuiTableFlags_RowBg | ImGuiTableFlags_SizingStretchProp)) {
			ImGui::TableSetupColumn("Address", ImGuiTableColumnFlags_WidthFixed, 160.f);
			ImGui::TableSetupColumn("Name", ImGuiTableColumnFlags_WidthStretch);
			ImGui::TableSetupColumn("Strings", ImGuiTableColumnFlags_WidthStretch);
			ImGui::TableHeadersRow();

			for (const auto& r : m_state.rows) {
				ImGui::TableNextRow();

				ImGui::TableSetColumnIndex(0);
				ImGui::Text("0x%016llX", static_cast<unsigned long long>(r.addr));

				ImGui::TableSetColumnIndex(1);
				ImGui::TextUnformatted(r.name.c_str());

				ImGui::TableSetColumnIndex(2);
				std::string joined;
				for (size_t i = 0; i < r.strings.size(); ++i) {
					if (i) joined += " | ";
					joined += r.strings[i];
				}
				ImGui::TextWrapped("%s", joined.c_str());
			}

			ImGui::EndTable();
		}
	}

	ImGui::Separator();
	if (!m_state.running && !m_state.rows.empty()) {
		ImGui::Text("Export Options:");

		if (ImGui::Button("Simple Text")) {
			std::string path;
			if (ExportResultsToText(path)) {
				LogInfo("Exported to: " + path);
			}
		}
		ImGui::SetItemTooltip("One line per function with pipe-separated strings");

		ImGui::SameLine();
		if (ImGui::Button("IDA Comments (.py)")) {
			std::string path;
			if (ExportToIDAPython(path)) {
				LogInfo("IDA script exported to: " + path);
				// Copy to clipboard
				if (OpenClipboard(nullptr)) {
					EmptyClipboard();
					HGLOBAL hg = GlobalAlloc(GMEM_MOVEABLE, path.size() + 1);
					if (hg) {
						memcpy(GlobalLock(hg), path.c_str(), path.size() + 1);
						GlobalUnlock(hg);
						SetClipboardData(CF_TEXT, hg);
					}
					CloseClipboard();
				}
			}
		}
		ImGui::SetItemTooltip("Generate IDA Python script to add string comments");

		ImGui::SameLine();
		if (ImGui::Button("Enhanced (.txt)")) {
			std::string path;
			if (ExportEnhancedResults(path)) {
				LogInfo("Enhanced export to: " + path);
			}
		}
		ImGui::SetItemTooltip("Detailed export with RVAs, bytes, and patterns");

		ImGui::SameLine();
		if (ImGui::Button("CSV")) {
			std::string path;
			if (ExportToCSV(path)) {
				LogInfo("CSV exported to: " + path);
			}
		}
		ImGui::SetItemTooltip("Spreadsheet-compatible format");

		ImGui::SameLine();
		if (ImGui::Button("Copy All Addresses")) {
			std::ostringstream ss;
			for (const auto& r : m_state.rows) {
				ss << "0x" << std::hex << r.addr << "\n";
			}
			std::string addresses = ss.str();
			if (OpenClipboard(nullptr)) {
				EmptyClipboard();
				HGLOBAL hg = GlobalAlloc(GMEM_MOVEABLE, addresses.size() + 1);
				if (hg) {
					memcpy(GlobalLock(hg), addresses.c_str(), addresses.size() + 1);
					GlobalUnlock(hg);
					SetClipboardData(CF_TEXT, hg);
				}
				CloseClipboard();
				LogInfo("Copied " + std::to_string(m_state.rows.size()) + " addresses to clipboard");
			}
		}
		ImGui::SetItemTooltip("Copy all function addresses to clipboard");
	}

	ImGui::End();
}

void StringXrefAnalyzer::StartAnalysis(int minStringLength, size_t maxStringsPerFunc)
{
	CancelAnalysis();
	m_state.running = true;
	m_state.minLen = std::max(3, minStringLength);
	m_state.maxStringsPerFn = std::max<size_t>(1, maxStringsPerFunc);
	m_state.totalAscii = 0;
	m_state.totalUtf16 = 0;
	m_state.rows.clear();
	m_state.interimMap.clear(); // NEW: reset interim accumulation
	m_state.status = "Preparing...";
	m_state.cancel.store(false, std::memory_order_relaxed);
	m_state.started = std::chrono::steady_clock::now();
	m_state.mapProcessed.store(0, std::memory_order_relaxed);
	m_state.mapTotal = 0;

	m_state.task = std::async(std::launch::async, [this]() {
		HMODULE mod = ::GetModuleHandleW(nullptr);
		if (!mod) { m_state.status = "Failed: no module"; m_state.running = false; return; }

		uint8_t* rdata = nullptr; size_t rdataSize = 0;
		if (!GetSectionRange(mod, ".rdata", rdata, rdataSize) || !rdata || rdataSize < 1024) {
			m_state.status = "Failed: .rdata not found"; m_state.running = false; return;
		}

		m_state.status = "Collecting strings...";
		const size_t asciiLimit = 25000;
		const size_t utf16Limit = 8000;

		std::vector<std::pair<uintptr_t, std::string>> asciiStrings;
		std::vector<std::pair<uintptr_t, std::string>> utf16Strings;

		CollectAsciiStrings(rdata, rdataSize, static_cast<size_t>(m_state.minLen), asciiLimit, asciiStrings);
		CollectUtf16Strings(rdata, rdataSize, static_cast<size_t>(m_state.minLen), utf16Limit, utf16Strings);
		m_state.totalAscii = asciiStrings.size();
		m_state.totalUtf16 = utf16Strings.size();

		m_state.mapTotal = m_state.totalAscii + m_state.totalUtf16;
		m_state.mapProcessed.store(0, std::memory_order_relaxed);

		m_state.status = "Mapping string references...";

		auto scanner = std::make_shared<SapphireHook::FunctionScanner>();
		auto mapBatch = [&](const std::vector<std::pair<uintptr_t, std::string>>& list) {
			for (const auto& kv : list) {
				if (m_state.cancel.load(std::memory_order_relaxed)) return;

				const uintptr_t saddr = kv.first;
				const std::string& s = kv.second;

				auto refs = SapphireHook::PatternScanner::FindRipReferencesTo(mod, saddr);
				if (!refs.empty()) {
					size_t refCap = 4;
					size_t taken = 0;
					for (auto ref : refs) {
						if (taken >= refCap) break;
						uintptr_t fn = scanner->FindFunctionStart(ref);
						if (!fn) continue;

						auto& vec = m_state.interimMap[fn]; // NEW: accumulate partials
						if (std::find(vec.begin(), vec.end(), s) == vec.end()) {
							vec.push_back(s);
							++taken;
						}
					}
				}

				// Progress update
				m_state.mapProcessed.fetch_add(1, std::memory_order_relaxed);
				if ((m_state.mapProcessed.load(std::memory_order_relaxed) & 0x3FF) == 0) {
					size_t done = m_state.mapProcessed.load(std::memory_order_relaxed);
					size_t total = m_state.mapTotal;
					m_state.status = "Mapping string references... " + std::to_string(done) + "/" + std::to_string(total);
				}
			}
			};

		mapBatch(asciiStrings);
		if (!m_state.cancel.load(std::memory_order_relaxed))
			mapBatch(utf16Strings);

		// Build rows from whatever we have (complete or partial)
		auto finalizeRows = [this]() {
			m_state.rows.clear();
			m_state.rows.reserve(m_state.interimMap.size());
			for (auto& [fn, strs] : m_state.interimMap) {
				if (strs.size() > m_state.maxStringsPerFn)
					strs.resize(m_state.maxStringsPerFn);
				XrefRow r;
				r.addr = fn;
				r.name = "";
				r.strings = std::move(strs);
				m_state.rows.emplace_back(std::move(r));
			}
			std::sort(m_state.rows.begin(), m_state.rows.end(),
				[](const auto& a, const auto& b) { return a.strings.size() > b.strings.size(); });
			};

		if (m_state.cancel.load(std::memory_order_relaxed)) {
			finalizeRows(); // NEW: produce partial results on cancel
			const auto ms = std::chrono::duration_cast<std::chrono::milliseconds>(
				std::chrono::steady_clock::now() - m_state.started).count();
			m_state.status = "Cancelled (" + std::to_string(m_state.rows.size()) + " funcs) in " + std::to_string(ms) + "ms";
			m_state.running = false;
			return;
		}

		finalizeRows(); // normal completion
		const auto ms = std::chrono::duration_cast<std::chrono::milliseconds>(
			std::chrono::steady_clock::now() - m_state.started).count();
		m_state.status = "Done in " + std::to_string(ms) + "ms";
		m_state.running = false;
		});
}

void StringXrefAnalyzer::CancelAnalysis()
{
	m_state.cancel.store(true, std::memory_order_relaxed);
	if (m_state.task.valid()) {
		try { m_state.task.wait(); }
		catch (...) {}
	}
	// Do not clear results on cancel; they were finalized (partial) in the worker if any
	if (!m_state.running && !m_state.rows.empty() && m_state.status.rfind("Cancelled", 0) != 0) {
		m_state.status = "Cancelled (" + std::to_string(m_state.rows.size()) + " funcs)";
	}
	m_state.running = false;
}

std::vector<StringXrefAnalyzer::XrefRow> StringXrefAnalyzer::GetResults() const
{
	return m_state.rows;
}

bool StringXrefAnalyzer::ExportResultsToText(std::string& outPath) const
{
	using SapphireHook::Logger;

	if (m_state.rows.empty()) return false;

	// Build a filename in the SapphireHook temp directory
	std::filesystem::path baseDir = Logger::GetDefaultTempDir();
	std::error_code ec;
	std::filesystem::create_directories(baseDir, ec);

	const auto now = std::chrono::system_clock::now();
	const auto tt = std::chrono::system_clock::to_time_t(now);
	std::tm tm{};
#if defined(_WIN32)
	localtime_s(&tm, &tt);
#else
	tm = *std::localtime(&tt);
#endif
	std::ostringstream name;
	name << "xref_results." << std::put_time(&tm, "%Y%m%d.%H%M%S") << ".txt";

	std::filesystem::path out = baseDir / name.str();

	std::ofstream ofs(out, std::ios::out | std::ios::trunc);
	if (!ofs.is_open()) {
		LogError(std::string("Export failed: could not open file: ") + out.string());
		return false;
	}

	// Header
	ofs << "String XREF Results\n";
	ofs << "====================\n\n";
	ofs << "Functions: " << m_state.rows.size()
		<< " | ASCII strings: " << m_state.totalAscii
		<< " | UTF-16 strings: " << m_state.totalUtf16 << "\n\n";

	// One function per line, strings joined with " | "
	for (const auto& r : m_state.rows) {
		// Address + name
		ofs << "0x" << std::hex << std::setw(16) << std::setfill('0')
			<< static_cast<unsigned long long>(r.addr) << std::dec << "  ";
		ofs << (r.name.empty() ? "(unnamed)" : r.name);

		// Joined strings
		if (!r.strings.empty()) {
			ofs << " | ";
			for (size_t i = 0; i < r.strings.size(); ++i) {
				std::string s = r.strings[i];
				// Sanitize any embedded newlines/tabs so the export stays one-line-per-function
				for (char& c : s) {
					if (c == '\r' || c == '\n' || c == '\t') c = ' ';
				}
				ofs << s;
				if (i + 1 < r.strings.size()) ofs << " | ";
			}
		}
		ofs << "\n";
	}

	ofs.flush();
	ofs.close();

	outPath = out.string();
	return true;
}

// Add these methods to StringXrefAnalyzer class:

// 1. Export to IDA Python script - just addresses and raw strings, no guessing
bool StringXrefAnalyzer::ExportToIDAPython(std::string& outPath) const
{
	if (m_state.rows.empty()) return false;

	std::filesystem::path baseDir = Logger::GetDefaultTempDir();
	std::error_code ec;
	std::filesystem::create_directories(baseDir, ec);

	const auto now = std::chrono::system_clock::now();
	const auto tt = std::chrono::system_clock::to_time_t(now);
	std::tm tm{};
	localtime_s(&tm, &tt);

	std::ostringstream name;
	name << "ida_xref_comments." << std::put_time(&tm, "%Y%m%d.%H%M%S") << ".py";

	std::filesystem::path out = baseDir / name.str();
	std::ofstream ofs(out, std::ios::out | std::ios::trunc);
	if (!ofs.is_open()) return false;

	HMODULE hMod = GetModuleHandleW(nullptr);
	uintptr_t imageBase = reinterpret_cast<uintptr_t>(hMod);

	// Generate IDA script that adds comments with string references
	ofs << "# IDA Pro String XREF Comments\n";
	ofs << "# Generated by SapphireHook StringXrefAnalyzer\n";
	ofs << "# Functions with strings: " << m_state.rows.size() << "\n\n";
	ofs << "import idaapi\n";
	ofs << "import idc\n\n";
	ofs << "# Runtime image base: 0x" << std::hex << imageBase << "\n";
	ofs << "ida_base = idaapi.get_imagebase()\n";
	ofs << "runtime_base = 0x" << std::hex << imageBase << "\n\n";
	ofs << "def rebase(addr):\n";
	ofs << "    return addr - runtime_base + ida_base\n\n";
	ofs << "commented = 0\n";
	ofs << "failed = 0\n\n";

	// Just add comments with the actual strings found
	for (const auto& r : m_state.rows) {
		ofs << "try:\n";
		ofs << "    addr = rebase(0x" << std::hex << r.addr << ")\n";

		// Build comment from strings
		ofs << "    comment = \"XREF Strings: ";
		for (size_t i = 0; i < r.strings.size(); ++i) {
			if (i) ofs << " | ";
			ofs << SanitizeForPython(r.strings[i]);
		}
		ofs << "\"\n";

		ofs << "    idc.set_func_cmt(addr, comment, 0)\n";  // Set as regular comment
		ofs << "    print(f\"Added comment at 0x{addr:X}\")\n";
		ofs << "    commented += 1\n";
		ofs << "except:\n";
		ofs << "    failed += 1\n\n";
	}

	ofs << "print(f\"\\nCompleted: {commented} comments added, {failed} failed\")\n";
	ofs.close();

	outPath = out.string();
	LogInfo("IDA Python script exported to: " + outPath);
	return true;
}

// 2. Export enhanced data with signatures and RVAs
bool StringXrefAnalyzer::ExportEnhancedResults(std::string& outPath) const
{
	if (m_state.rows.empty()) return false;

	std::filesystem::path baseDir = Logger::GetDefaultTempDir();
	std::error_code ec;
	std::filesystem::create_directories(baseDir, ec);

	const auto now = std::chrono::system_clock::now();
	const auto tt = std::chrono::system_clock::to_time_t(now);
	std::tm tm{};
	localtime_s(&tm, &tt);

	std::ostringstream name;
	name << "xref_enhanced." << std::put_time(&tm, "%Y%m%d.%H%M%S") << ".txt";

	std::filesystem::path out = baseDir / name.str();
	std::ofstream ofs(out, std::ios::out | std::ios::trunc);
	if (!ofs.is_open()) {
		LogError(std::string("Export failed: could not open file: ") + out.string());
		return false;
	}

	HMODULE hMod = GetModuleHandleW(nullptr);
	uintptr_t imageBase = reinterpret_cast<uintptr_t>(hMod);

	ofs << "String XREF Analysis - IDA Pro Enhanced Export\n";
	ofs << "===============================================\n\n";
	ofs << "Image Base: 0x" << std::hex << imageBase << std::dec << "\n";
	ofs << "Analysis Time: " << std::put_time(&tm, "%Y-%m-%d %H:%M:%S") << "\n";
	ofs << "Functions: " << m_state.rows.size() << " | ASCII: " << m_state.totalAscii
		<< " | UTF-16: " << m_state.totalUtf16 << "\n\n";

	for (const auto& r : m_state.rows) {
		uintptr_t rva = r.addr - imageBase;

		ofs << "================================================================================\n";
		ofs << "VA:  0x" << std::hex << std::setw(16) << std::setfill('0') << r.addr << "\n";
		ofs << "RVA: 0x" << std::hex << std::setw(8) << std::setfill('0') << rva << "\n";

		// Read first 64 bytes for signature
		uint8_t bytes[64] = { 0 };
		SIZE_T bytesRead = 0;
		if (ReadProcessMemory(GetCurrentProcess(),
			reinterpret_cast<LPCVOID>(r.addr),
			bytes, sizeof(bytes), &bytesRead)) {
			ofs << "Bytes: ";
			for (size_t i = 0; i < std::min(bytesRead, (SIZE_T)32); ++i) {
				ofs << std::hex << std::setw(2) << std::setfill('0')
					<< (int)bytes[i] << " ";
			}
			ofs << "\n";

			// Generate IDA-style pattern (with wildcards for calls/jumps)
			ofs << "Pattern: ";
			for (size_t i = 0; i < std::min(bytesRead, (SIZE_T)32); ++i) {
				// After E8/E9 (CALL/JMP), next 4 bytes are relative
				if (bytes[i] == 0xE8 || bytes[i] == 0xE9) {
					ofs << std::hex << std::setw(2) << std::setfill('0')
						<< (int)bytes[i] << " ? ? ? ? ";
					i += 4; // Skip displacement
				}
				// RIP-relative addressing
				else if (i + 6 < bytesRead && bytes[i] == 0x48 &&
					(bytes[i + 1] == 0x8D || bytes[i + 1] == 0x8B) &&
					(bytes[i + 2] & 0xC7) == 0x05) {
					ofs << std::hex << std::setw(2) << std::setfill('0') << (int)bytes[i] << " ";
					ofs << std::hex << std::setw(2) << std::setfill('0') << (int)bytes[i + 1] << " ";
					ofs << std::hex << std::setw(2) << std::setfill('0') << (int)bytes[i + 2] << " ";
					ofs << "? ? ? ? ";
					i += 6;
				}
				else {
					ofs << std::hex << std::setw(2) << std::setfill('0')
						<< (int)bytes[i] << " ";
				}
			}
			ofs << "\n";
		}

		ofs << std::dec << "String Count: " << r.strings.size() << "\n";
		ofs << "Strings:\n";
		for (const auto& s : r.strings) {
			ofs << "  \"" << s << "\"\n";
		}
		ofs << "\n";
	}

	ofs.close();
	outPath = out.string();
	return true;
}

// 3. Export as CSV for easy spreadsheet analysis
bool StringXrefAnalyzer::ExportToCSV(std::string& outPath) const
{
	if (m_state.rows.empty()) return false;

	std::filesystem::path baseDir = Logger::GetDefaultTempDir();
	std::error_code ec;
	std::filesystem::create_directories(baseDir, ec);

	const auto now = std::chrono::system_clock::now();
	const auto tt = std::chrono::system_clock::to_time_t(now);
	std::tm tm{};
	localtime_s(&tm, &tt);

	std::ostringstream name;
	name << "xref_results." << std::put_time(&tm, "%Y%m%d.%H%M%S") << ".csv";

	std::filesystem::path out = baseDir / name.str();
	std::ofstream ofs(out, std::ios::out | std::ios::trunc);
	if (!ofs.is_open()) return false;

	HMODULE hMod = GetModuleHandleW(nullptr);
	uintptr_t imageBase = reinterpret_cast<uintptr_t>(hMod);

	// CSV header
	ofs << "\"Address\",\"RVA\",\"String Count\",\"Strings\"\n";

	for (const auto& r : m_state.rows) {
		uintptr_t rva = r.addr - imageBase;

		ofs << "\"0x" << std::hex << r.addr << "\",";
		ofs << "\"0x" << std::hex << rva << "\",";
		ofs << std::dec << r.strings.size() << ",\"";

		// Join strings with pipe delimiter
		for (size_t i = 0; i < r.strings.size(); ++i) {
			if (i) ofs << " | ";
			// Escape quotes in CSV
			std::string s = r.strings[i];
			for (char& c : s) {
				if (c == '"') ofs << "\"\"";
				else if (c == '\r' || c == '\n' || c == '\t') c = ' ';
				else ofs << c;
			}
		}
		ofs << "\"\n";
	}

	ofs.close();
	outPath = out.string();
	return true;
}

// 4. Helper to sanitize strings for Python
std::string StringXrefAnalyzer::SanitizeForPython(const std::string& str) const
{
	std::string result;
	for (char c : str) {
		if (c == '"') result += "\\\"";
		else if (c == '\\') result += "\\\\";
		else if (c == '\n') result += "\\n";
		else if (c == '\r') result += "\\r";
		else if (c == '\t') result += "\\t";
		else if (c >= 32 && c <= 126) result += c;
		else {
			// Non-printable as hex escape
			char buf[5];
			std::snprintf(buf, sizeof(buf), "\\x%02x", (unsigned char)c);
			result += buf;
		}
	}
	return result;
}